image: node:20
pages:
  cache:
    paths:
      - docs/node_modules/
  script:
    - ls
    - cd docs
    - ls
    - yarn
    - yarn docs:build
    - ls
    - cd ..
    - mv docs/dist public
    # - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    # - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public
  tags:
    - node
  only:
    - main
