image: node:20
pages:
  cache:
    paths:
      - docs/node_modules/
  script:
    - cd docs
    - yarn
    - yarn docs:build
    - mv .vitepress/dist ../public
  artifacts:
    paths:
      - public
  tags:
    - node
  only:
    - main
