image: node:20
pages:
  cache:
    paths:
      - node_modules/
  script:
    - cd docs
    - yarn
    - yarn docs:build --base=$CI_PAGES_URL
  artifacts:
    paths:
      - public
  tags:
    - node
  only:
    - main
