services:
  frankenphp:
    ports: !override
      - ${HTTP_PORT:-80}:80
    networks:
      - puc-network
    volumes:
      - './symfony/public/media:/app/public/media'
      - './symfony/public/files:/app/public/files'
  postgres:
    networks:
      - puc-network
  nominatim:
    networks:
      - puc-network
  qgis:
    networks:
      - puc-network
  osm2pgsql:
    networks:
      - puc-network

networks:
  puc-network:
    name: puc_network
    external: true
