services:
  vue:
    build:
      target: vue_prod
      args:
        - VITE_SENTRY_DSN=${SENTRY_DSN}

  docs:
    build:
      target: docs_prod

  frankenphp:
    build:
      context: ./symfony
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - ./symfony/docker/caddy/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./symfony/docker/caddy/worker.Caddyfile:/etc/caddy/worker.Caddyfile
    networks:
      - puc-network
  nominatim:
    networks:
      - puc-network

  mailserver:
    image: mailserver/docker-mailserver:${DOCKER_MAILSERVER_VERSION:-14.0.0}
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.${DOMAIN}
    ports:
      - "${SMTP_RELAY_PORT:-25}:25"
      - "${SMTP_OLD_PORT:-465}:465"
      - "${SMTP_SUBMISSION_PORT:-587}:587"
      - "${IMAP_PORT:-993}:993"
    volumes:
      - ./docker/mailserver/dms/mail-data/:/var/mail/
      - ./docker/mailserver/dms/mail-state/:/var/mail-state/
      - ./docker/mailserver/dms/mail-logs/:/var/log/mail/
      - ./docker/mailserver/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always

networks:
  puc-network:
    name: puc_network
