services:
  frankenphp:
    ports: !override
      - ${HTTP_PORT:-80}:80
    networks:
      - puc-network
  postgres:
    networks:
      - puc-network
  nominatim:
    networks:
      - puc-network

networks:
  puc-network:
    name: puc_network