services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\State\:
        resource: '../../../src/State/'

    App\State\Processor\UserProcessor:
        bind:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'