services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Services\Service\EmailVerifier\:
    resource: '../../../src/Services/Service/EmailVerifier/'

  App\Services\Service\EmailVerifier\EmailVerifierService:
      bind:
          int $lifetime: '%email_verifier.lifetime%'

  App\Services\Service\EmailVerifier\EmailVerifierTokenGenerator:
    bind:
      string $secret: '%env(APP_SECRET)%'

