# Read the documentation: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/master/Resources/doc/getting_started.md
coop_tilleuls_forgot_password:
    password_token:
        class: App\Entity\User\UserPasswordToken
        expires_in: 1 day
        user_field: user
        serialization_groups: [!php/const App\Entity\User\UserPasswordToken::GROUP_READ]
    user:
        class: App\Entity\User\User # required
        email_field: email
        password_field: password
