lexik_jwt_authentication:
    token_extractors:
        authorization_header:
            enabled: false

        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s

    set_cookies:
        jwt_hp:
            lifetime: null
            samesite: strict
            path: /
            domain: puc.local
            httpOnly: false
            split:
                - header
                - payload

        jwt_s:
            lifetime: 0
            samesite: strict
            path: /
            domain: puc.local
            httpOnly: true
            split:
                - signature

    # remove the token from the response body when using cookies
    remove_token_from_body_when_cookies_used: false

    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'