lexik_jwt_authentication:
    token_extractors:
        authorization_header:
            enabled: false

        cookie:
            enabled: true
            name: BEARER
    
    set_cookies:
        BEARER: ~

    # remove the token from the response body when using cookies
    remove_token_from_body_when_cookies_used: false

    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'