services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Event\EventListener\:
        resource: '../../../src/Event/EventListener/'

    App\Event\EventListener\UserListener:
        tags:
          - { name: kernel.event_listener, event: kernel.exception }


      #   App\Event\EventListener\UserListener:
      # tags:
      #     -
      #       name: doctrine.orm.entity_listener
      #       event: preUpdate
      #       entity: App\Entity\User